language: node_js
node_js:
- 6
- 4
install:
- npm install
- npm install -g mocha
deploy:
  provider: npm
  email:
    secure: jPJIR6UHfttfZvw5YiFgy+g/WQFJ+q5wYk4MsamJ6fD4NOaw71ZXWbaqEb9If1cJ1eyd2WszW+kq4G2ec0ReZTukyry0WkGeNkIGJFR3nAU5pjbswKeaoie1D3LC4xHjz8zNQRrwg7nbKUtkla6mjiDPiK2OjrZ+fT/EsHaFqpoIqWvw0IZhWaPB+U1g0Umr+SKXzfREWVnckfp86r1j/Mr2R4sEzWjHWsYUAU0HLHdVteatKL442ngS2UOe/dT3PtkHTfpsVaa4954SF97M3Rx6GO5lZ9Mv5n8yWagIXMbe4a4/KUuGzkR0ss5F3C6kJ1t5XjYYfc2kv3+j+1U2qg4ajey4fhYxRMPX0yPYd/wVguwJpW9ALdnCTKD+SaZe8a3RJBkmNygdLCYa8Bcg98ITz+1XYdOq3AfasoN/fcZGThZ14sTRwW7Si8BT7KS50Fv+YMOEJrdrkMMKSq6MLNEaDC1JhX0HUXZ7u1T+t/1BW09KNrL+j5bf3xf3JHkTkJ2qaylvPFefptUGi5grf/qfvEHlI8nlVPlDabLlQdnLlm+jqLAdeLjFQ+rG+usgx7tMdlC9LxPUl2hKVZthXqtLmFM0IaaaiG03wo1cgcWWnThNOTIq8wynqisQ73AHX617YMLDsbMFdqcvr2YPNWmbpW4SgRLhHkFA9osUqdw=
  api_key:
    secure: ew0Bao98dPww45KWTMDMDB9VLEyPwlAJ7i5rnGYucnchMt8rU91bk1aKjKeqR2J4EPXENbRdU+61DrpdkXqkoUrQRMBzkZZ5hFPWBLElrIdnOwAh4SwLf6U9P/g2BLPNYeyk7wJuWUhEK3JtG8dnXlbRhfL+AK0DewLQMkE+fb5iWdZgw1o282d/HjbvadCREUjY2tGBkeUo+nYhgQDsgXkm1X6r8HJo5qRr5q4BsjeHKrs2xke67qXIJLP5ilTrKxX3lz+aT4S5jVcI1VEjxeZOBu/SsHsOhJ7ddIHd+0jcCYJkZMVlIq9U5NknY535/1D7X22KTFU/unTGadL/v3uHm5pn0Yi8LZR3L4VZFpUBK1zWESxGzrzGcZ3nNTJA0otO/93A591qI1ZeJsI3TNCMJvdtR2nKtz1hiBSsOEARZe8KNVbWsvTTSLABqqwq5eWawDMMM1hLsTTF/Wh0C5L6pr0pkiM5EchCJStvv9w7mAlD1/9nb3/J1IwWBb/gAJclj3LJU3JXHWSg7KXS2vvSIJzuR7IpjzpBe8z/bV2v+puwSKXnkDeTPDly/iM0eSggsnrOKmWN/yOuQBgYUkXUayoq95q9Z79luNJrayPbAE1P49X3+13ULtTI66fvrcFAVnIkH75DH3V1Ax/Ty5QMY886kAOihE2FFGYLiYw=
  on:
    tags: true
